### ISSUE TITLE
open source the dataset and source code

### ISSUE THREAD

**Issue by srijithrajeev** [haitaobiyao/MCNet#1]
Hi,
It would be very helpful if you could provide the timeline for open-sourcing the source code and the dataset. 
Best,
Srijith

**Comment by haitaobiyao** [comment]
Thanks for noticing our work, and sorry for the inconvenience caused by not uploading our dataset and code in time, we will upload the dataset and code by July 5th.

**Comment by haitaobiyao** [comment]
> Hi,
> It would be very helpful if you could provide the timeline for open-sourcing the source code and the dataset.
> Best,
> Srijith

Thanks for noticing our work, and sorry for the inconvenience caused by not uploading our dataset and code in time, we will upload the dataset and code before July 5th.
